/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalculationRequestCustom {

  /**
   * DateTime in format: yyyy-MM-dd HH:mm:ss or in format: yyyy-MM-dd HH:mm:ss.ffffff
   */
  dateTime: string;

  /**
   * Sometimes a time can be ambiguous due to DST switching.
   * For example, suppose the time zone goes backward
   * at 2am, so the second after 01:59:59 becomes 01:00:00. In that case,
   * times such as 01:30:00 occur twice. By using "earlier" it uses the earlier version of 01:30:00 where 01:59:59 hasn't been passed.
   * By using "later" it uses the later version of 01:30:00 where the time has passed 01:59:59.
   */
  dstAmbiguity?: string | null;

  /**
   * Time span to increase or decrease datetime by in format: d:hh:mm:ss or in format: d:hh:mm:ss.fff
   */
  timeSpan: string;

  /**
   * IANA TimeZone
   */
  timeZone: string;
}
