/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CalculationResult } from '../models/calculation-result';
export interface Calculation {
  calculationResult?: CalculationResult;

  /**
   * Original DateTime given
   */
  originalDateTime?: string;

  /**
   * IANA Timezone used
   */
  timeZone?: string | null;

  /**
   * The timespan used to increase or decrease the original datetime by in format: d:hh:mm:ss
   */
  usedTimeSpan?: string | null;
}
