/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CalculationRequestCurrent {

  /**
   * Time span to increase or decrease datetime by in format: d:hh:mm:ss or in format: d:hh:mm:ss.fff
   */
  timeSpan: string;

  /**
   * IANA TimeZone
   */
  timeZone: string;
}
