/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConversionResult } from '../models/conversion-result';
export interface Conversion {
  conversionResult?: ConversionResult;
  fromDateTime?: string;
  fromTimezone?: string | null;
  toTimeZone?: string | null;
}
