/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayOfWeek } from '../models/day-of-week';
export interface CurrentTime {

  /**
   * Date string
   */
  date?: string | null;

  /**
   * Full date time
   */
  dateTime?: string;

  /**
   * Day
   */
  day?: number;
  dayOfWeek?: DayOfWeek;

  /**
   * Boolean describing whether DST is applied and active in that timezone
   */
  dstActive?: boolean;

  /**
   * Hour of the day in range 0-24
   */
  hour?: number;

  /**
   * Milliseconds
   */
  milliSeconds?: number;

  /**
   * Minute
   */
  minute?: number;

  /**
   * Month
   */
  month?: number;

  /**
   * Second
   */
  seconds?: number;

  /**
   * Time string
   */
  time?: string | null;

  /**
   * TimeZone of the result
   */
  timeZone?: string | null;

  /**
   * Year
   */
  year?: number;
}
