/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Duration } from '../models/duration';
import { Offset } from '../models/offset';
export interface DstInterval {
  dstDuration?: Duration;
  dstEnd?: string | null;
  dstName?: string | null;
  dstOffsetToStandardTime?: Offset;
  dstOffsetToUtc?: Offset;
  dstStart?: string | null;
}
