/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Duration {
  bclCompatibleTicks?: number;
  days?: number;
  hours?: number;
  milliseconds?: number;
  minutes?: number;
  nanosecondOfDay?: number;
  seconds?: number;
  subsecondNanoseconds?: number;
  subsecondTicks?: number;
  totalDays?: number;
  totalHours?: number;
  totalMilliseconds?: number;
  totalMinutes?: number;
  totalNanoseconds?: number;
  totalSeconds?: number;
  totalTicks?: number;
}
