/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Offset {
  milliseconds?: number;
  nanoseconds?: number;
  seconds?: number;
  ticks?: number;
}
