/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DstInterval } from '../models/dst-interval';
import { Offset } from '../models/offset';
export interface TimeZoneData {
  currentLocalTime?: string;
  currentUtcOffset?: Offset;
  dstInterval?: DstInterval;
  hasDayLightSaving?: boolean;
  isDayLightSavingActive?: boolean;
  standardUtcOffset?: Offset;
  timeZone?: string | null;
}
