/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Translation {

  /**
   * Given date time to translate
   */
  dateTime?: string | null;

  /**
   * Translated date
   */
  friendlyDate?: string | null;

  /**
   * Full translated date time
   */
  friendlyDateTime?: string | null;

  /**
   * Translated time
   */
  friendlyTime?: string | null;

  /**
   * Given language code to translate the date time into
   */
  languageCode?: string | null;
}
