/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Conversion } from '../../models/conversion';
import { ConvertRequest } from '../../models/convert-request';

export interface ApiConversionConverttimezonePost$Params {
      body?: ConvertRequest
}

export function apiConversionConverttimezonePost(http: HttpClient, rootUrl: string, params?: ApiConversionConverttimezonePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Conversion>> {
  const rb = new RequestBuilder(rootUrl, apiConversionConverttimezonePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Conversion>;
    })
  );
}

apiConversionConverttimezonePost.PATH = '/api/conversion/converttimezone';
