/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DayOfTheWeekResult } from '../../models/day-of-the-week-result';

export interface ApiConversionDayoftheweekDateGet$Params {

/**
 * Date in format: yyyy-MM-dd
 */
  date: string;
}

export function apiConversionDayoftheweekDateGet(http: HttpClient, rootUrl: string, params: ApiConversionDayoftheweekDateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DayOfTheWeekResult>> {
  const rb = new RequestBuilder(rootUrl, apiConversionDayoftheweekDateGet.PATH, 'get');
  if (params) {
    rb.path('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DayOfTheWeekResult>;
    })
  );
}

apiConversionDayoftheweekDateGet.PATH = '/api/conversion/dayoftheweek/{date}';
