/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { TimeApiConfiguration, TimeApiConfigurationParams } from './time-api-configuration';

import { TimeService } from './services/time.service';
import { TimeZoneService } from './services/time-zone.service';
import { ConversionService } from './services/conversion.service';
import { CalculationService } from './services/calculation.service';
import { HealthService } from './services/health.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    TimeService,
    TimeZoneService,
    ConversionService,
    CalculationService,
    HealthService,
    TimeApiConfiguration
  ],
})
export class TimeApiModule {
  static forRoot(params: TimeApiConfigurationParams): ModuleWithProviders<TimeApiModule> {
    return {
      ngModule: TimeApiModule,
      providers: [
        {
          provide: TimeApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: TimeApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('TimeApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
