/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class TimeApiConfiguration {
  rootUrl: string = '';
}

/**
 * Parameters for `TimeApiModule.forRoot()`
 */
export interface TimeApiConfigurationParams {
  rootUrl?: string;
}
