/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentTime } from '../../models/current-time';

export interface ApiTimeCurrentZoneGet$Params {

/**
 * Full IANA time zone names.
 */
  timeZone?: string;
}

export function apiTimeCurrentZoneGet(http: HttpClient, rootUrl: string, params?: ApiTimeCurrentZoneGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentTime>> {
  const rb = new RequestBuilder(rootUrl, apiTimeCurrentZoneGet.PATH, 'get');
  if (params) {
    rb.query('timeZone', params.timeZone, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentTime>;
    })
  );
}

apiTimeCurrentZoneGet.PATH = '/api/time/current/zone';
