/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { TimeApiConfiguration } from '../time-api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiHealthCheckGet } from '../fn/health/api-health-check-get';
import { ApiHealthCheckGet$Params } from '../fn/health/api-health-check-get';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: TimeApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiHealthCheckGet()` */
  static readonly ApiHealthCheckGetPath = '/api/health/check';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthCheckGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthCheckGet$Response(params?: ApiHealthCheckGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHealthCheckGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthCheckGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthCheckGet(params?: ApiHealthCheckGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHealthCheckGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
