/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { TimeApiConfiguration } from '../time-api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTimeCurrentCoordinateGet } from '../fn/time/api-time-current-coordinate-get';
import { ApiTimeCurrentCoordinateGet$Params } from '../fn/time/api-time-current-coordinate-get';
import { apiTimeCurrentIpGet } from '../fn/time/api-time-current-ip-get';
import { ApiTimeCurrentIpGet$Params } from '../fn/time/api-time-current-ip-get';
import { apiTimeCurrentZoneGet } from '../fn/time/api-time-current-zone-get';
import { ApiTimeCurrentZoneGet$Params } from '../fn/time/api-time-current-zone-get';
import { CurrentTime } from '../models/current-time';

@Injectable({ providedIn: 'root' })
export class TimeService extends BaseService {
  constructor(config: TimeApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTimeCurrentZoneGet()` */
  static readonly ApiTimeCurrentZoneGetPath = '/api/time/current/zone';

  /**
   * Gets the current time of a time zone.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeCurrentZoneGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentZoneGet$Response(params?: ApiTimeCurrentZoneGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentTime>> {
    return apiTimeCurrentZoneGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current time of a time zone.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeCurrentZoneGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentZoneGet(params?: ApiTimeCurrentZoneGet$Params, context?: HttpContext): Observable<CurrentTime> {
    return this.apiTimeCurrentZoneGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentTime>): CurrentTime => r.body)
    );
  }

  /** Path part for operation `apiTimeCurrentCoordinateGet()` */
  static readonly ApiTimeCurrentCoordinateGetPath = '/api/time/current/coordinate';

  /**
   * Gets the current time of a time zone by geo coordinates.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeCurrentCoordinateGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentCoordinateGet$Response(params?: ApiTimeCurrentCoordinateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentTime>> {
    return apiTimeCurrentCoordinateGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current time of a time zone by geo coordinates.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeCurrentCoordinateGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentCoordinateGet(params?: ApiTimeCurrentCoordinateGet$Params, context?: HttpContext): Observable<CurrentTime> {
    return this.apiTimeCurrentCoordinateGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentTime>): CurrentTime => r.body)
    );
  }

  /** Path part for operation `apiTimeCurrentIpGet()` */
  static readonly ApiTimeCurrentIpGetPath = '/api/time/current/ip';

  /**
   * Gets the current time of a time zone by ip address.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeCurrentIpGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentIpGet$Response(params?: ApiTimeCurrentIpGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentTime>> {
    return apiTimeCurrentIpGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current time of a time zone by ip address.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeCurrentIpGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeCurrentIpGet(params?: ApiTimeCurrentIpGet$Params, context?: HttpContext): Observable<CurrentTime> {
    return this.apiTimeCurrentIpGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentTime>): CurrentTime => r.body)
    );
  }

}
