/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeZoneData } from '../../models/time-zone-data';

export interface ApiTimezoneIpGet$Params {

/**
 * IPv4 address
 */
  ipAddress?: string;
}

export function apiTimezoneIpGet(http: HttpClient, rootUrl: string, params?: ApiTimezoneIpGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeZoneData>> {
  const rb = new RequestBuilder(rootUrl, apiTimezoneIpGet.PATH, 'get');
  if (params) {
    rb.query('ipAddress', params.ipAddress, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeZoneData>;
    })
  );
}

apiTimezoneIpGet.PATH = '/api/timezone/ip';
