/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeZoneData } from '../../models/time-zone-data';

export interface ApiTimezoneCoordinateGet$Params {

/**
 * Latitude ranging from -90 to 90
 */
  latitude?: number;

/**
 * Longitude ranging from -180 to 180
 */
  longitude?: number;
}

export function apiTimezoneCoordinateGet(http: HttpClient, rootUrl: string, params?: ApiTimezoneCoordinateGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeZoneData>> {
  const rb = new RequestBuilder(rootUrl, apiTimezoneCoordinateGet.PATH, 'get');
  if (params) {
    rb.query('latitude', params.latitude, {});
    rb.query('longitude', params.longitude, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeZoneData>;
    })
  );
}

apiTimezoneCoordinateGet.PATH = '/api/timezone/coordinate';
