/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeZoneData } from '../../models/time-zone-data';

export interface ApiTimezoneZoneGet$Params {

/**
 * Full IANA time zone name.
 */
  timeZone?: string;
}

export function apiTimezoneZoneGet(http: HttpClient, rootUrl: string, params?: ApiTimezoneZoneGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeZoneData>> {
  const rb = new RequestBuilder(rootUrl, apiTimezoneZoneGet.PATH, 'get');
  if (params) {
    rb.query('timeZone', params.timeZone, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeZoneData>;
    })
  );
}

apiTimezoneZoneGet.PATH = '/api/timezone/zone';
